services:
  anon:
    image: latentdiff_anon
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
     - "7860:7860"
    volumes:
      # masks
      - ./data/masks:/data/masks 
      # images
      - ../data/images:/data/images
      # anonymized (output images)
      - ./data/anonymized:/data/anonymized
      # weights
      - ./models/stable-diffusion:/opt/gui/models/Stable-diffusion
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
