services:
  anon:
    image: latentdiff_anon
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
     - "${PORT}:7860"
    volumes:
      - ${MASKS_VOLUME}:/data/masks
      - ${IMAGES_VOLUME}:/data/images
      - ${ANONYMIZED_VOLUME}:/data/anonymized
      -  .models/stable-diffusion:/opt/gui/models/Stable-diffusion
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['${DEVICE_ID}']
            capabilities: [gpu]
